# Meta Data for SEO

## Homepage
title = "Simran Verma"
titleSeparator = ""
titleAddition = ""
description = "Simran Verma"

## Open Graph + Twitter Cards
images = [""]
twitterSite = "simmranvermaa"
twitterCreator = "simmranvermaa"
facebookAuthor = "simmranvermaa"
facebookPublisher = "simmranvermaa"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = ""
schemaTwitter = "https://twitter.com/simmranvermaa"
schemaLinkedIn = "https://www.linkedin.com/in/simmranvermaa/"
schemaGitHub = "https://github.com/simmranvermaa"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "© Simran Verma"

# Edit Page
#docsRepo = ""
#editPage = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = false
  darkMode = true
  bootStrapJs = false
  breadCrumb = false
  highLight = true
  kaTex = false
